map_type: costmap
footprint: [ [-0.05,-0.125] ,[0.35,-0.125], [0.35,0.125], [-0.05,0.125]]
obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 2.5
 inflation_radius: 0.20
 track_unknown_space: false
 combination_method: 1
 observation_sources: laser_scan_sensor point_cloud_sensor
 laser_scan_sensor: {
  sensor_frame: laser , 
  data_type: LaserScan , 
  topic: /scan , 
  marking: true, 
  clearing: true
 }
 point_cloud_sensor: {
  sensor_frame: camera_depth_frame, 
  data_type: PointCloud2, 
  topic: /ransac_objects, 
  marking: true, 
  clearing: false,
 }


inflation_layer:
  enabled:              true
  cost_scaling_factor:  2.58  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.75  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
